### ISSUE TITLE
Get easily the info of the avaibility of an employee

### ISSUE THREAD

**Issue by aegiap** [sayoun/pyvac#10]
I would like to know if a colleague is present or not with a simple method. 
 - maybe a API call (REST ?) ?
   for example: api.available('Sarah Connor',  date) with the date param optional and set to today if empty,
 - maybe a web page for each employee with a status for the day ?
 - maybe another method.

**Comment by sayoun** [comment]
Closing this, commit https://github.com/sayoun/pyvac/commit/bac8844f024dacd928b977fee89bdda346b863ea should answer the need:

- Fixes issue #10: Add a new route to query for users presence
  * route url is /pyvac/off
  * can be filtered by date (default today) /pyvac/off?date=20151224
  * can be filtered by name (can be partial) /pyvac/off?name=peter
  * can be filtered by nickame (LDAP uid field) (can be partial) /pyvac/off?nick=spiderman
