### ISSUE TITLE
Show the half-day leave in the summary

### ISSUE THREAD

**Issue by aegiap** [sayoun/pyvac#7]
In the /request URL, where all the paid leave and RTT asked are listed, the half-day requested leave does not show if the request is for the morning or the afternoon.

Step to reproduce the issue:
 * login on the pyvac system,
 * request a RTT for either the morning (AM) or the afternoon (PM) and submit,
 * go to the requests page and check the list of requested leave. It shows 'Number 0.5' for the day without the specific info of which half of the day.

**Comment by sayoun** [comment]
It's done in commit de8d6711c8501c98a38a9bd73765c4a6363db2b2
Closing this issue.
