### ISSUE TITLE
Show employee vacation in the employee calendar

### ISSUE THREAD

**Issue by aegiap** [sayoun/pyvac#9]
On the main page of pyvac instance, when I try to request for a vacation I do not remember where I already have a vacation.

Can we have information in the calendar of which days or half-days are requested and which days or half-days are validated (idealy two colors).

Thank you

**Comment by romuald** [comment]
:+1:

**Comment by zaurky** [comment]
:+1:

**Comment by sayoun** [comment]
Done in release 1.7 for full days.

Will see later how to properly handle half-days without overloading the calendar display
